spring.application.name=tesouraria

# porta da aplicação
server.port=8080

# conexão com banco MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tesouraria
spring.datasource.username=root
spring.datasource.password=

# driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# cria tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# mostra SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true